<inh f='include/c++/4.8/exception' l='60' c='std::exception'/>
<def f='include/c++/4.8/stdexcept' l='112' ll='127'/>
<ovr f='include/c++/4.8/stdexcept' l='130' c='std::range_error'/>
<ovr f='include/c++/4.8/stdexcept' l='138' c='std::overflow_error'/>
<ovr f='include/c++/4.8/stdexcept' l='146' c='std::underflow_error'/>
<ovr f='ceres-solver/internal/ceres/gtest/gtest.h' l='7893' c='testing::internal::GoogleTestFailureException'/>
<size>16</size>
<doc f='include/c++/4.8/stdexcept' l='107'>/** Runtime errors represent problems outside the scope of a program;
   *  they cannot be easily predicted and can generally only be caught as
   *  the program executes.
   *  @brief One of two subclasses of exception.
   */</doc>
<mbr r='std::runtime_error::_M_msg' o='64' t='string'/>
<fun r='_ZNSt13runtime_errorC1ERKSs'/>
<fun r='_ZNSt13runtime_errorD1Ev'/>
<fun r='_ZNKSt13runtime_error4whatEv'/>
